#!/usr/bin/env python3
"""Deterministic P2-17 core data type generator."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path
from typing import Any


def canonical_json(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, indent=2, sort_keys=True) + "\n"


def sha256_bytes(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def sha256_file(path: Path) -> str:
    return sha256_bytes(path.read_bytes())


def pascal_name(domain: str) -> str:
    leaf = domain.rsplit("/", 1)[-1]
    parts = [part for part in re.split(r"[^A-Za-z0-9]+", leaf) if part]
    if not parts:
        raise ValueError(f"domain has no portable identifier: {domain}")
    name = "".join(part[0].upper() + part[1:] for part in parts)
    if not re.fullmatch(r"[A-Z][A-Za-z0-9]*", name):
        raise ValueError(f"domain produced an invalid identifier: {domain}")
    return name


def build_model(registry: dict[str, Any], audit: dict[str, Any], policy_sha: str) -> dict[str, Any]:
    audit_components = {
        (entry["domain"], entry["column_id"]): entry for entry in audit["components"]
    }
    models: list[dict[str, Any]] = []
    names: set[str] = set()
    for table in registry["tables"]:
        domain = table["logical_name"]
        name = pascal_name(domain)
        if name in names:
            raise ValueError(f"generated model name collision: {name}")
        names.add(name)
        key_columns = set(table["primary_key"]["column_ids"])
        fields: list[dict[str, Any]] = []
        for column in table["columns"]:
            column_id = column["id"]
            source_type = column["type"]
            is_identity = column_id in key_columns
            if is_identity:
                component = audit_components.get((domain, column_id))
                if component is None:
                    raise ValueError(f"audit component is missing: {domain}/{column_id}")
                if source_type == "int64":
                    if component["required_sign"] != "unsigned":
                        raise ValueError(f"numeric identity is not proven unsigned: {domain}/{column_id}")
                    storage_type = "uint64"
                elif source_type == "string":
                    storage_type = "utf8-string"
                else:
                    raise ValueError(f"unsupported identity source type: {source_type}")
            else:
                storage_type = {
                    "int64": "int64",
                    "decimal": "double",
                    "string": "utf8-string",
                }.get(source_type)
                if storage_type is None:
                    raise ValueError(f"unsupported value source type: {source_type}")
            fields.append(
                {
                    "column_id": column_id,
                    "name": column_id.upper(),
                    "nullable": bool(column["nullable"]),
                    "role": "identity-component" if is_identity else "value",
                    "source_type": source_type,
                    "storage_type": storage_type,
                }
            )
        models.append(
            {
                "domain": domain,
                "fields": fields,
                "id_type": f"{name}Id",
                "name": name,
                "record_type": f"{name}Record",
            }
        )
    return {
        "models": models,
        "policy": {
            "narrowing": "forbidden",
            "numeric_identity_storage": "uint64",
            "sha256": policy_sha,
        },
        "schema_id": "tmxy-core-data-model-v1",
        "schema_version": 1,
        "source": {
            "core_table_registry_sha256": "",
            "id_limit_audit_sha256": "",
        },
        "task_id": "P2-17",
    }


def cpp_type(field: dict[str, Any], target: str) -> str:
    storage = field["storage_type"]
    if target == "backend":
        base = {
            "uint64": "std::uint64_t",
            "int64": "std::int64_t",
            "double": "double",
            "utf8-string": "std::string",
        }[storage]
        return f"std::optional<{base}>" if field["nullable"] else base
    base = {
        "uint64": "uint64",
        "int64": "int64",
        "double": "double",
        "utf8-string": "FString",
    }[storage]
    return f"TOptional<{base}>" if field["nullable"] else base


def render_backend(model: dict[str, Any], schema_sha: str) -> str:
    lines = [
        "// Generated by TMXY.ProtocolGen. Do not edit by hand.",
        f"// Source schema SHA-256: {schema_sha}",
        "#pragma once",
        "",
        "#include <cstddef>",
        "#include <cstdint>",
        "#include <optional>",
        "#include <string>",
        "",
        "namespace tmxy::contracts::data",
        "{",
        f"inline constexpr std::size_t model_count = {len(model['models'])}U;",
        "",
    ]
    for entry in model["models"]:
        identity = [field for field in entry["fields"] if field["role"] == "identity-component"]
        values = [field for field in entry["fields"] if field["role"] == "value"]
        lines.extend([f"struct {entry['id_type']} final", "{"])
        for field in identity:
            lines.append(f"    {cpp_type(field, 'backend')} {field['name']}{{}};")
        lines.extend(
            [
                "",
                f"    [[nodiscard]] friend bool operator==(const {entry['id_type']}&, const {entry['id_type']}&) = default;",
                "};",
                "",
                f"struct {entry['record_type']} final",
                "{",
                f"    {entry['id_type']} Id{{}};",
            ]
        )
        for field in values:
            lines.append(f"    {cpp_type(field, 'backend')} {field['name']}{{}};")
        lines.extend(["};", ""])
    lines.extend(["} // namespace tmxy::contracts::data", ""])
    return "\n".join(lines)


def render_ue(model: dict[str, Any], schema_sha: str) -> str:
    lines = [
        "// Generated by TMXY.ProtocolGen. Do not edit by hand.",
        f"// Source schema SHA-256: {schema_sha}",
        "#pragma once",
        "",
        '#include "CoreMinimal.h"',
        '#include "Misc/Optional.h"',
        "",
        "namespace TMXY::Contracts::Data",
        "{",
        f"inline constexpr int32 ModelCount = {len(model['models'])};",
        "",
    ]
    for entry in model["models"]:
        identity = [field for field in entry["fields"] if field["role"] == "identity-component"]
        values = [field for field in entry["fields"] if field["role"] == "value"]
        lines.extend([f"struct F{entry['id_type']} final", "{"])
        for field in identity:
            lines.append(f"    {cpp_type(field, 'ue')} {field['name']}{{}};")
        lines.extend(
            [
                "",
                f"    bool operator==(const F{entry['id_type']}&) const = default;",
                "};",
                "",
                f"struct F{entry['record_type']} final",
                "{",
                f"    F{entry['id_type']} Id{{}};",
            ]
        )
        for field in values:
            lines.append(f"    {cpp_type(field, 'ue')} {field['name']}{{}};")
        lines.extend(["};", ""])
    lines.extend(["} // namespace TMXY::Contracts::Data", ""])
    return "\n".join(lines)


def describe_output(path: Path) -> dict[str, Any]:
    data = path.read_bytes()
    return {
        "bytes": len(data),
        "lines": len(data.splitlines()),
        "sha256": sha256_bytes(data),
    }


def generate(args: argparse.Namespace) -> dict[str, Any]:
    registry_path = Path(args.registry)
    audit_path = Path(args.audit)
    policy_path = Path(args.policy)
    registry = json.loads(registry_path.read_text(encoding="utf-8"))
    audit = json.loads(audit_path.read_text(encoding="utf-8"))
    policy = json.loads(policy_path.read_text(encoding="utf-8"))
    if registry.get("task_id") != "P2-07" or audit.get("task_id") != "P2-11":
        raise ValueError("P2-07 registry and P2-11 audit are required")
    if policy["identity"]["numeric_storage"] != "uint64" or policy["identity"]["narrowing"] != "forbidden":
        raise ValueError("policy must prohibit narrowing and select uint64 identities")
    model = build_model(registry, audit, sha256_file(policy_path))
    model["source"]["core_table_registry_sha256"] = sha256_file(registry_path)
    model["source"]["id_limit_audit_sha256"] = sha256_file(audit_path)
    schema_text = canonical_json(model)
    schema_sha = sha256_bytes(schema_text.encode("utf-8"))
    outputs = {
        "schema": (Path(args.schema_output), schema_text),
        "backend": (Path(args.backend_output), render_backend(model, schema_sha)),
        "ue": (Path(args.ue_output), render_ue(model, schema_sha)),
    }
    for path, text in outputs.values():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8", newline="\n")
    fields = [field for entry in model["models"] for field in entry["fields"]]
    summary = {
        "identity_components": sum(field["role"] == "identity-component" for field in fields),
        "models": len(model["models"]),
        "nullable_fields": sum(field["nullable"] for field in fields),
        "outputs": {name: describe_output(path) for name, (path, _) in outputs.items()},
        "source_fields": len(fields),
        "targets": 2,
    }
    return summary


def self_test() -> dict[str, Any]:
    assert pascal_name("CLSVShare/item_table") == "ItemTable"
    assert pascal_name("CLSVShare/LevelInfo") == "LevelInfo"
    numeric = {"nullable": False, "storage_type": "uint64"}
    string_optional = {"nullable": True, "storage_type": "utf8-string"}
    assert cpp_type(numeric, "backend") == "std::uint64_t"
    assert cpp_type(numeric, "ue") == "uint64"
    assert cpp_type(string_optional, "backend") == "std::optional<std::string>"
    assert cpp_type(string_optional, "ue") == "TOptional<FString>"
    return {"assertions": 6, "result": "PASS"}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--self-test", action="store_true")
    parser.add_argument("--registry")
    parser.add_argument("--audit")
    parser.add_argument("--policy")
    parser.add_argument("--schema-output")
    parser.add_argument("--backend-output")
    parser.add_argument("--ue-output")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if args.self_test:
        print(json.dumps(self_test(), sort_keys=True))
        return 0
    required = [args.registry, args.audit, args.policy, args.schema_output, args.backend_output, args.ue_output]
    if any(value is None for value in required):
        raise ValueError("all generation paths are required")
    print(json.dumps(generate(args), sort_keys=True))
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, ValueError, KeyError, TypeError, json.JSONDecodeError) as error:
        print(f"protocol_gen: {error}", file=sys.stderr)
        raise SystemExit(2)
